
version: '3'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  web_server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
  
    links:
      - db

volumes:
  db_data:


