version: "3"

services:
  go-app:
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/.env
      - ./logs.log:/logs.log
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

