server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: MARKETPLACE-APP

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

