version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./error.log:/app/error.log
  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
