version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5555:5432"

  marketplace-app:
    build:
      context: ./
    container_name: marketplace-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    volumes:
      - ../build/libs/marketplace.jar:/app/marketplace.jar

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../frontend:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - marketplace-app


