version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"

  eureka-registry:
    build:
      context: service-registry
    container_name: registry
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
      EUREKA_CLIENT_FETCH_REGISTRY: false
    volumes:
      - ./service-registry/build/libs/registry.jar:/app/registry.jar

  api-gateway:
    build:
      context: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - marketplace-app
      - eureka-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/
    volumes:
      - ./gateway/build/libs/gateway.jar:/app/gateway.jar

  auth-service:
    build:
      context: auth-service
    container_name: auth
    ports:
      - "9898:9898"
    depends_on:
      - postgres
      - eureka-registry
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/
    volumes:
      - ./auth-service/build/libs/auth.jar:/app/auth.jar

  marketplace-app:
    build:
      context: marketplace-service
    container_name: marketplace
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-registry
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-registry:8761/eureka/
    volumes:
      - ./marketplace-service/build/libs/marketplace.jar:/app/marketplace.jar








